void main(){

  int i = 0;
  int num = 10;
  	try{
   		var sum = num/i;
   		print(sum);
	}
	catch(e){
		print("An error occured : $e ");
	}
}